
// Auto-generated by AutoPilot on 07-08-2023 at 03:21:16

const express = require('express');
const router = express.Router();

//Generate random number 0 or 1
//0 = heads and 1 = tails
router.get('/coinFlip', (req, res) => {
    let randNum = Math.round(Math.random());
    let result = (randNum === 0) ? "heads" : "tails";
    res.json({ result });
});

module.exports = router;